# Generated by Django 2.0.3 on 2018-03-25 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaName', models.CharField(db_column='name', max_length=63)),
                ('marcaDescription', models.CharField(db_column='description', max_length=123)),
                ('marcaUuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Optica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opticaName', models.CharField(db_column='name', max_length=123)),
                ('opticaDirection', models.CharField(db_column='direction', max_length=255)),
                ('opticaContact1', models.IntegerField(db_column='contact_number_1')),
                ('opticaContact2', models.IntegerField(db_column='contact_number_2')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provName', models.CharField(db_column='name', error_messages={'unique': 'Este nombre ya se encuentra asignado a otro proveedor.'}, max_length=123, unique=True)),
                ('provDirection', models.CharField(blank=True, db_column='direction', max_length=255)),
                ('provContact1', models.PositiveIntegerField(db_column='contact_number_1')),
                ('provContact2', models.PositiveIntegerField(db_column='contact_number_2', null=True)),
                ('provUuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='marcaProveedorFK',
            field=models.ForeignKey(db_column='proveedor', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.Proveedor'),
        ),
    ]
