# Generated by Django 2.0.3 on 2018-03-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180324_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='marcaDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marcaName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marcaProveedorFK',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marcaUuid',
            new_name='uuid',
        ),
    ]
