# Generated by Django 2.0.3 on 2018-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180325_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contact_2',
            field=models.PositiveIntegerField(blank=True, db_column='contact_number_2', default=-1),
            preserve_default=False,
        ),
    ]
