# Generated by Django 2.0.3 on 2018-05-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180414_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Proveedor'),
        ),
    ]
