# Generated by Django 2.0.3 on 2018-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180507_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=123),
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('name', 'proveedor')},
        ),
    ]
