# Generated by Django 2.0.3 on 2018-05-15 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20180512_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=123)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('color', models.CharField(max_length=31)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Marca')),
            ],
        ),
    ]
