# Generated by Django 2.0.3 on 2018-05-19 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_aro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optica',
            old_name='opticaDirection',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='optica',
            old_name='opticaName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='optica',
            name='contact_1',
            field=models.PositiveIntegerField(db_column='contact_number_1', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optica',
            name='contact_2',
            field=models.PositiveIntegerField(db_column='contact_number_2', null=True),
        ),
        migrations.AddField(
            model_name='optica',
            name='email',
            field=models.EmailField(blank=True, db_column='email', default='correo@correo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='aro',
            name='color',
            field=models.CharField(max_length=31, validators=[django.core.validators.RegexValidator(message='Patrón inválido, sólo se aceptan letras, números,espacios, _, # y -', regex='^[0-9A-Za-z\\#_\\-\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='aro',
            name='modelo',
            field=models.CharField(max_length=123, validators=[django.core.validators.RegexValidator(message='Patrón inválido, sólo se aceptan letras, números, _, # y -', regex='^[0-9A-Za-z\\#_\\-\\s]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='aro',
            unique_together={('modelo', 'marca', 'color')},
        ),
        migrations.RemoveField(
            model_name='optica',
            name='opticaContact1',
        ),
        migrations.RemoveField(
            model_name='optica',
            name='opticaContact2',
        ),
        migrations.AlterUniqueTogether(
            name='optica',
            unique_together={('name', 'direction')},
        ),
    ]
