# Generated by Django 2.0.3 on 2018-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20180518_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='optica',
            name='contact_1',
            field=models.PositiveIntegerField(db_column='contact_1'),
        ),
        migrations.AddField(
            model_name='optica',
            name='contact_2',
            field=models.PositiveIntegerField(db_column='contact_2', null=True),
        ),
    ]
