# Generated by Django 2.0.3 on 2018-05-19 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20180518_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='optica',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
