# Generated by Django 2.0.3 on 2018-05-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_optica_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibles', models.SmallIntegerField()),
                ('perdidas', models.SmallIntegerField(default=0)),
                ('ventas', models.SmallIntegerField(default=0)),
                ('aro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Aro')),
                ('optica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Optica')),
            ],
        ),
    ]
