# Generated by Django 2.0.3 on 2018-05-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_inventario_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='total',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aro',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aros', to='inventario.Marca'),
        ),
    ]
