# Generated by Django 2.0.3 on 2018-05-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20180522_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='total',
        ),
    ]
