# Generated by Django 2.0.3 on 2018-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_inventario_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponibles',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
