# Generated by Django 2.0.3 on 2018-05-26 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20180525_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', error_messages={'unique': 'Este nombre ya se encuentra asignado a otro proveedor.'}, max_length=123, unique=True)),
                ('direction', models.CharField(db_column='directions', max_length=255)),
                ('contact_1', models.PositiveIntegerField()),
                ('contact_2', models.PositiveIntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
