# Generated by Django 2.0.3 on 2018-05-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='direction',
            field=models.CharField(blank=True, db_column='directions', max_length=255),
        ),
    ]
