# Generated by Django 2.0.3 on 2018-05-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20180526_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.CharField(max_length=127)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=127)),
                ('tipo', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
                ('filtro', models.ManyToManyField(to='inventario.Filtro')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lente',
            unique_together={('material', 'tipo', 'color')},
        ),
    ]
