# Generated by Django 2.0.3 on 2018-05-26 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20180526_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='lente',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
