# Generated by Django 2.0.3 on 2018-05-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_auto_20180526_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lente',
            name='filtro',
            field=models.ManyToManyField(blank=True, to='inventario.Filtro'),
        ),
    ]
