# Generated by Django 2.0.3 on 2018-07-05 18:51

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_auto_20180529_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='optica',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=inventario.models.optica_path, verbose_name='Logo'),
        ),
    ]
