# Generated by Django 2.0.3 on 2018-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_optica_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aro',
            name='sexo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aro',
            name='tipo',
            field=models.SmallIntegerField(default=0),
        ),
    ]
