# Generated by Django 2.0.3 on 2018-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20180715_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='optica',
            name='redes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
