# Generated by Django 2.0.3 on 2018-05-30 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0021_auto_20180529_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.PositiveIntegerField(null=True)),
                ('contact', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.FileField(blank=True, max_length=255, null=True, upload_to=ordenes.models.user_directory_path, verbose_name='Profile picture')),
                ('optica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Optica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
