# Generated by Django 2.0.3 on 2018-05-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20180529_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.BigIntegerField(null=True),
        ),
    ]
