# Generated by Django 2.0.3 on 2018-05-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_auto_20180529_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
    ]
