# Generated by Django 2.0.3 on 2018-06-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_remove_empleado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='optica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Optica'),
        ),
    ]
