# Generated by Django 2.0.3 on 2018-06-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_auto_20180615_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='surname',
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('firstname', 'lastname', 'secondname', 'contact_1')},
        ),
    ]
