# Generated by Django 2.0.3 on 2018-06-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_auto_20180616_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('firstname', 'lastname', 'contact_1')},
        ),
    ]
