# Generated by Django 2.0.3 on 2018-06-22 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_aro_orden_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='aro_orden',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
