# Generated by Django 2.0.3 on 2018-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_abono_aro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='aro_orden',
            name='entrega',
            field=models.DateTimeField(default='2018-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono_aro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aro_orden',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
