# Generated by Django 2.0.3 on 2018-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_auto_20180625_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aro_orden',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
