# Generated by Django 2.0.3 on 2018-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_auto_20180625_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono_aro',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
