# Generated by Django 2.0.3 on 2018-07-01 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0021_auto_20180629_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono_Completa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(default=1)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_completa', to='ordenes.Completa_Orden')),
            ],
        ),
        migrations.AddField(
            model_name='clientrefraction',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abono_aro',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
