# Generated by Django 2.0.3 on 2018-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_auto_20180630_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refraction',
            name='prismaOD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='prismaOS',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
