# Generated by Django 2.0.3 on 2018-07-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0023_auto_20180701_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='cilOSF',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
