# Generated by Django 2.0.3 on 2018-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_refraction_cilosf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrefraction',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='refraction',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
