# Generated by Django 2.0.3 on 2018-07-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0028_auto_20180706_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refraction',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refraction', to='ordenes.Cliente'),
        ),
    ]
