# Generated by Django 2.0.3 on 2018-07-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_auto_20180706_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='aro_orden',
            name='notas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='completa_orden',
            name='costolente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='completa_orden',
            name='notas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
