# Generated by Django 2.0.3 on 2018-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_auto_20180715_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='refraction',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
