# Generated by Django 2.0.3 on 2018-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0032_refraction_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aro_orden',
            name='notas',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
