# Generated by Django 2.0.3 on 2018-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0033_auto_20180718_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completa_orden',
            name='notas',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
