# Generated by Django 2.0.3 on 2018-07-20 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0034_auto_20180718_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono_completa',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 7, 20, 7, 28, 10, 230576, tzinfo=utc)),
        ),
    ]
