# Generated by Django 2.0.3 on 2018-07-29 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0035_auto_20180720_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono_completa',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
