# Generated by Django 2.0.3 on 2018-07-30 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_optica_redes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0036_auto_20180728_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono_Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(default=1)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abono_Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(default=1)),
                ('pago', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lente_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_id', models.IntegerField(null=True)),
                ('ventalente', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('pagado', models.PositiveSmallIntegerField(default=0)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('notas', models.CharField(blank=True, max_length=1023)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('entrega', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.Cliente')),
                ('filtros', models.ManyToManyField(related_name='lente_filtros', to='inventario.Filtro')),
                ('lente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lente_lente', to='inventario.Lente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Repair_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aro', models.CharField(max_length=123)),
                ('offline_id', models.IntegerField(null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('pagado', models.PositiveSmallIntegerField(default=0)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('notas', models.CharField(blank=True, max_length=1023)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('entrega', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='aro_orden',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='refraction',
            name='tipo',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='abono_repair',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_repair', to='ordenes.Repair_Orden'),
        ),
        migrations.AddField(
            model_name='abono_lente',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_lente', to='ordenes.Lente_Orden'),
        ),
    ]
