# Generated by Django 2.0.3 on 2018-07-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0037_auto_20180729_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lente_orden',
            old_name='ventalente',
            new_name='costolente',
        ),
    ]
