# Generated by Django 2.0.3 on 2018-07-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_optica_redes'),
        ('ordenes', '0038_auto_20180729_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='completa_orden',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_completa', to='inventario.Laboratorio'),
        ),
        migrations.AddField(
            model_name='lente_orden',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_lente', to='inventario.Laboratorio'),
        ),
    ]
